ТЗ 9
Scandi7/java-kanban pull request #4
Opened 2024-06-29 11:46 UTC by Scandi7

2024-06-29 11:50 UTC, Scandi7 commented
Здравствуйте, Евгений. Надеюсь, вы видите это сообщение. Во время тестов столкнулся с такой ошибкой com.google.gson.JsonIOException: Failed making field 'java.time.Duration#seconds' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
See https://github.com/google/gson/blob/main/Troubleshooting.md#reflection-inaccessible
Может вы сталкивались с подобной ошибкой и знаете как легко и быстро ее исправить?

2024-06-30 05:42 UTC, EugeneLenkevich requested changes
Привет, Даниил! Спасибо за PR.

Ошибка что ты скинул похоже связана с настройками сериализации. С ходу не вижу причину, лучше сразу спроси куратора, у них больше информации и кто то уже, скорее всего, с таким сталкивался
Возможно надо подкрутить TypeAdapter
https://howtodoinjava.com/gson/gson-typeadapter-for-inaccessibleobjectexception/

И закомментированные тест лучше или починить или вовсе убрать чтобы не мешались, лучше конечно починить :)

2024-06-30 05:42 UTC, EugeneLenkevich commented on src/main/HttpTaskServer.java
> +        this.gson = new GsonBuilder()
Так и просится создание объекта gson вынести в отдельный метод, чтобы избежать дублирования. Плюс так его изменения его настроек станут централизованными :)

2024-06-30 09:58 UTC, EugeneLenkevich approved these changes
А ошибку в итоге получилось победить?

2024-06-30 10:51 UTC, Scandi7 commented
> А ошибку в итоге получилось победить?
Если коротко, то решить ошибку помогло добавление "кастомного" TypeAdapter для LocalDateTime и Duration. 
Сама idea ругалась на эту строчку 
String jsonInputString = gson.toJson(task); преобразование объекта таск в JSON строку

А теперь чуть подлиннее
Ошибка возникала в старых тестах, там адаптеры были написаны немного по другому(видимо неправильно). Я менял код, пытаясь исправить ошибку, в "основных" классах если можно так сказать . В конце концов запутался что, где и для чего менял. Зато теперь появилось четкое понимание, что по мере того, как пишешь код, надо его сохранять, чтобы потом в случае чего откатиться. Старые тесты просто закомментировал и добавил новые. Переделал TypeAdapter. Сейчас вот вернулся к старым тестам и да, ошибка была просто в криво написанном TypeAdapter

2024-06-30 16:28 UTC, merged